### ISSUE TITLE
Could u kindly share the real experimental datasets?

### ISSUE THREAD

**Issue by stefenmax** [hariagr/R2CT#1]
Hi, I am working with the multi-task problem(ring artifact and noise). But I don't have the real experimental data to verify my algorithms.

And I saw u paper to have these datas. Could u kindly share the real experimental datasets?

Thanks

Best wishes

**Comment by hariagr** [comment]
Hi,

Probably, the Tomobank datasets would be helpful for your case; see
https://tomobank.readthedocs.io/en/latest/source/data.html.

Hari

**Comment by stefenmax** [comment]
Thank u very much.
